name: "telekeeper_web"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - selenium
    - postgres

  # Uncomment to use capybara tests with Selenium
  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  postgres:
    image: postgres:18beta2-alpine
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  plantuml-server:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    restart: unless-stopped
    ports:
      - "8081:8080"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
        - "11434:11434"
    volumes:
        - ollama-data:/root/.ollama

volumes:
  ollama-data:
  postgres-data:
