# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

require 'google/protobuf'


descriptor_data = "\n\x12user_service.proto\x12\x0cuser_service\"\x0f\n\rCreateRequest\"\x10\n\x0e\x43reateResponse2X\n\x0bUserService\x12I\n\nCreateUser\x12\x1b.user_service.CreateRequest\x1a\x1c.user_service.CreateResponse\"\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module UserService
  CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user_service.CreateRequest").msgclass
  CreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user_service.CreateResponse").msgclass
end
