# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user_service.proto for package 'user_service'

require 'grpc'
require 'user_service_pb'

module UserService
  module UserService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user_service.UserService'

      rpc :CreateUser, ::UserService::CreateRequest, ::UserService::CreateResponse
    end

    Stub = Service.rpc_stub_class
  end
end
